services:
  backend:
    build: .
    ports:
      - 8080:8000
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "vk-pg"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local