"""porno 1488

Revision ID: 37a962073526
Revises: 985073519dde
Create Date: 2024-07-05 12:09:50.082196

Cum shot in my ass"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a962073526'
down_revision: Union[str, None] = '985073519dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'title')
    # ### end Alembic commands ###
